name: Build Windows Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          gcc --version
          pwd
          ls
          make clean
          make CC=gcc CFLAGS="-O3 -march=x86-64-v2 -Wall -std=c11 -Iinclude"
        shell: bash

      - name: Rename
        run: |
          pwd
          ls -la
          mv LittleGrandmaster LittleGrandmaster-Windows-x86_64.exe
          ls -la
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LittleGrandmaster-Windows-x86_64
          path: LittleGrandmaster-Windows-x86_64.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: LittleGrandmaster-Windows-x86_64.exe
          body: "Little Grandmaster ${{ github.ref_name }} - Windows x86_64 binary"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}